name: docker-typical-build-push
description: Builds a stage out of a dockerfile while caching the staged chain

inputs:
  dockerfile:
    required: true
    description: "Dockerfile to build."

  target-stage:
    required: true
    description: "Stage to build."

  upstream-stage:
    required: false
    description: "Name of the upstream stage that the target stage depends on."

  build-name:
    required: true
    description: "Name of the build."

  build-args:
    required: false
    description: "Build arguments to pass to docker."

runs:
  using: "composite"
  steps:
    - name: checkout-self
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: setup-buildx
      uses: docker/setup-buildx-action@v3

    - name: setup-login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: normalized-repository-name
      id: normalized-repository-name
      uses: ./.github/actions/normalize
      with:
        string: ${{ github.repository }}

    - name: normalized-target-stage
      id: normalized-target-stage
      uses: ./.github/actions/normalize
      with:
        string: ${{ inputs.target-stage }}

    - name: normalized-upstream-stage
      id: normalized-upstream-stage
      uses: ./.github/actions/normalize
      with:
        string: ${{ inputs.upstream-stage }}

    - name: normalized-build-name
      id: normalized-build-name
      uses: ./.github/actions/normalize
      with:
        string: ${{ inputs.build-name }}

    - name: git-tags
      id: git-tags
      uses: digital-ai/query-tag-action@v2
      with:
        commit-ish: HEAD
        exact-match: 'true'
        include: 'v*'
        skip-unshallow: 'true'

    - name: docker-metadata
      id: docker-metadata
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ steps.normalized-repository-name.outputs.string }}-${{ steps.normalized-target-stage.outputs.string }}-${{ steps.normalized-build-name.outputs.string }}
        tags: |
          type=raw,value=${{ github.sha }}
          type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
          type=raw,value=${{ steps.git-tags.outputs.tag }},enable=${{ contains(steps.git-tags.outputs.tag, 'NO_TAGS') == false }}

    - name: docker-stage-build
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        target: ${{ inputs.target-stage }}
        push: true
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
        cache-from: |
          ${{ inputs.upstream-stage != '' && format('type=registry,mode=max,ref=ghcr.io/{0}-{1}-{2}:buildcache', steps.normalized-repository-name.outputs.string, steps.normalized-upstream-stage.outputs.string, steps.normalized-build-name.outputs.string) || '' }}
          type=registry,mode=max,ref=ghcr.io/${{ steps.normalized-repository-name.outputs.string }}-${{ steps.normalized-target-stage.outputs.string }}-${{ steps.normalized-build-name.outputs.string }}:buildcache
        cache-to: |
          type=registry,mode=max,ref=ghcr.io/${{ steps.normalized-repository-name.outputs.string }}-${{ steps.normalized-target-stage.outputs.string }}-${{ steps.normalized-build-name.outputs.string }}:buildcache
        build-args: |
          ${{ inputs.build-args }}
