set(CMAKE_HOST_SYSTEM_NAME "Linux")
set(CMAKE_C_COMPILER /usr/bin/clang)
set(CMAKE_CXX_COMPILER /usr/bin/clang++)
set(CMAKE_Fortran_COMPILER /usr/bin/flang-new)
set(CMAKE_CUDA_COMPILER /usr/local/cuda-13/bin/nvcc)
set(CMAKE_CUDA_HOST_COMPILER /usr/bin/clang)
set(CMAKE_CUDA_ARCHITECTURES 75;80)
