name: nioc-build

on:
  workflow_run:
    workflows: [ "nioc-dev-base" ]
    types: [ completed ]

jobs:
  image-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os_base:
          - ubuntu:22.04
          - ubuntu:24.04
        toolchain:
          - linux-clang-19
          - linux-gnu-default

    steps:
      - name: nioc-build
        uses: ajakhotia/infraCommons/.github/actions/docker-typical-build-push@main
        with:
          dockerfile: docker/ubuntu.dockerfile
          password: ${{ secrets.GITHUB_TOKEN }}
          target-stage: nioc-build
          target-stage-id: build
          upstream-stage-id: dev-base
          build-name: ${{ matrix.os_base }}-${{ matrix.toolchain }}
          build-args: |
            OS_BASE=${{ matrix.os_base }}
            TOOLCHAIN=${{ matrix.toolchain }}
