name: nioc-base

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main

jobs:
  base-image-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os_base:
          - ubuntu:22.04
          - ubuntu:24.04
    steps:
      - name: checkout-self
        uses: ./.github/actions/docker-typical-build-push
        with:
          dockerfile: docker/ubuntu.dockerfile
          target-stage: nioc-base
          build-name: ${{ matrix.os_base }}
          build-args: |
            OS_BASE=${{ matrix.os_base }}
